#!/usr/bin/env bash
#0924_eff4_real_clipart_no_aug_round_3_v3.sh
#0924_eff4_real_painting_no_aug_round_3_v3.sh
#0924_eff5_real_clipart_no_aug_round_3_v3.sh
#0924_eff5_real_painting_no_aug_round_3_v3.sh
#0924_eff6_real_clipart_no_aug_round_3_v3.sh
#0924_eff6_real_painting_no_aug_round_3_v3.sh
#0924_eff7_real_clipart_no_aug_round_3_v3.sh
#0924_eff7_real_painting_no_aug_round_3_v3.sh
#0924_inception_real_clipart_no_aug_round_3_v3.sh
#0924_inception_real_painting_no_aug_round_3_v3.sh
#0924_se101_real_clipart_no_aug_round_3_v3.sh
#0924_se101_real_painting_no_aug_round_3_v3.sh
#0924_se152_real_clipart_no_aug_round_3_v3.sh
#0924_se152_real_painting_no_aug_round_3_v3.sh
#
#pseudo_label_round_3_0924_v3-models-0924_eff4_real_clipart_no_aug_round_3_v3_snapshot_netG_20.pth
#pseudo_label_round_3_0924_v3-models-0924_eff4_real_painting_no_aug_round_3_v3_snapshot_netG_18.pth
#pseudo_label_round_3_0924_v3-models-0924_eff5_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth
#pseudo_label_round_3_0924_v3-models-0924_eff5_real_painting_no_aug_round_3_v3_snapshot_netG_16.pth
#pseudo_label_round_3_0924_v3-models-0924_eff6_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth
#pseudo_label_round_3_0924_v3-models-0924_eff6_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth
#pseudo_label_round_3_0924_v3-models-0924_eff7_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth
#pseudo_label_round_3_0924_v3-models-0924_eff7_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth
#pseudo_label_round_3_0924_v3-models-0924_inception_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth
#pseudo_label_round_3_0924_v3-models-0924_inception_real_painting_no_aug_round_3_v3_snapshot_netG_12.pth
#pseudo_label_round_3_0924_v3-models-0924_se101_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth
#pseudo_label_round_3_0924_v3-models-0924_se101_real_painting_no_aug_round_3_v3_snapshot_netG_11.pth
#pseudo_label_round_3_0924_v3-models-0924_se152_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth
#pseudo_label_round_3_0924_v3-models-0924_se152_real_painting_no_aug_round_3_v3_snapshot_netG_9.pth

CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff4_real_clipart_no_aug_round_3_v3_snapshot_netG_20.pth --output_path experiments/full_set_predictions/0924_eff4_real_clipart_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff4_real_painting_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_eff4_real_painting_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff5_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_eff5_real_clipart_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff5_real_painting_no_aug_round_3_v3_snapshot_netG_16.pth --output_path experiments/full_set_predictions/0924_eff5_real_painting_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff6_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth --output_path experiments/full_set_predictions/0924_eff6_real_clipart_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff6_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth --output_path experiments/full_set_predictions/0924_eff6_real_painting_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff7_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth --output_path experiments/full_set_predictions/0924_eff7_real_clipart_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff7_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth --output_path experiments/full_set_predictions/0924_eff7_real_painting_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_inception_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_inception_real_clipart_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_inception_real_painting_no_aug_round_3_v3_snapshot_netG_12.pth --output_path experiments/full_set_predictions/0924_inception_real_painting_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se101_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth --output_path experiments/full_set_predictions/0924_se101_real_clipart_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se101_real_painting_no_aug_round_3_v3_snapshot_netG_11.pth --output_path experiments/full_set_predictions/0924_se101_real_painting_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se152_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth --output_path experiments/full_set_predictions/0924_se152_real_clipart_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se152_real_painting_no_aug_round_3_v3_snapshot_netG_9.pth --output_path experiments/full_set_predictions/0924_se152_real_painting_no_aug_round_3_v3.txt --multi_crop 1 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64


CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff4_real_clipart_no_aug_round_3_v3_snapshot_netG_20.pth --output_path experiments/full_set_predictions/0924_eff4_real_clipart_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff4_real_painting_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_eff4_real_painting_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff5_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_eff5_real_clipart_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff5_real_painting_no_aug_round_3_v3_snapshot_netG_16.pth --output_path experiments/full_set_predictions/0924_eff5_real_painting_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff6_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth --output_path experiments/full_set_predictions/0924_eff6_real_clipart_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff6_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth --output_path experiments/full_set_predictions/0924_eff6_real_painting_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff7_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth --output_path experiments/full_set_predictions/0924_eff7_real_clipart_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff7_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth --output_path experiments/full_set_predictions/0924_eff7_real_painting_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_inception_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_inception_real_clipart_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_inception_real_painting_no_aug_round_3_v3_snapshot_netG_12.pth --output_path experiments/full_set_predictions/0924_inception_real_painting_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se101_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth --output_path experiments/full_set_predictions/0924_se101_real_clipart_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se101_real_painting_no_aug_round_3_v3_snapshot_netG_11.pth --output_path experiments/full_set_predictions/0924_se101_real_painting_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se152_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth --output_path experiments/full_set_predictions/0924_se152_real_clipart_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se152_real_painting_no_aug_round_3_v3_snapshot_netG_9.pth --output_path experiments/full_set_predictions/0924_se152_real_painting_no_aug_round_3_v3_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64


CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff4_real_clipart_no_aug_round_3_v3_snapshot_netG_20.pth --output_path experiments/full_set_predictions/0924_eff4_real_clipart_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff4_real_painting_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_eff4_real_painting_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff5_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_eff5_real_clipart_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff5_real_painting_no_aug_round_3_v3_snapshot_netG_16.pth --output_path experiments/full_set_predictions/0924_eff5_real_painting_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff6_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth --output_path experiments/full_set_predictions/0924_eff6_real_clipart_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff6_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth --output_path experiments/full_set_predictions/0924_eff6_real_painting_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff7_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth --output_path experiments/full_set_predictions/0924_eff7_real_clipart_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff7_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth --output_path experiments/full_set_predictions/0924_eff7_real_painting_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_inception_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_inception_real_clipart_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_inception_real_painting_no_aug_round_3_v3_snapshot_netG_12.pth --output_path experiments/full_set_predictions/0924_inception_real_painting_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se101_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth --output_path experiments/full_set_predictions/0924_se101_real_clipart_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se101_real_painting_no_aug_round_3_v3_snapshot_netG_11.pth --output_path experiments/full_set_predictions/0924_se101_real_painting_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se152_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth --output_path experiments/full_set_predictions/0924_se152_real_clipart_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se152_real_painting_no_aug_round_3_v3_snapshot_netG_9.pth --output_path experiments/full_set_predictions/0924_se152_real_painting_no_aug_round_3_v3_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64


CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff4_real_clipart_no_aug_round_3_v3_snapshot_netG_20.pth --output_path experiments/full_set_predictions/0924_eff4_real_clipart_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff4_real_painting_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_eff4_real_painting_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff5_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_eff5_real_clipart_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff5_real_painting_no_aug_round_3_v3_snapshot_netG_16.pth --output_path experiments/full_set_predictions/0924_eff5_real_painting_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff6_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth --output_path experiments/full_set_predictions/0924_eff6_real_clipart_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff6_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth --output_path experiments/full_set_predictions/0924_eff6_real_painting_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff7_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth --output_path experiments/full_set_predictions/0924_eff7_real_clipart_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_eff7_real_painting_no_aug_round_3_v3_snapshot_netG_8.pth --output_path experiments/full_set_predictions/0924_eff7_real_painting_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_inception_real_clipart_no_aug_round_3_v3_snapshot_netG_18.pth --output_path experiments/full_set_predictions/0924_inception_real_clipart_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_inception_real_painting_no_aug_round_3_v3_snapshot_netG_12.pth --output_path experiments/full_set_predictions/0924_inception_real_painting_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se101_real_clipart_no_aug_round_3_v3_snapshot_netG_13.pth --output_path experiments/full_set_predictions/0924_se101_real_clipart_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se101_real_painting_no_aug_round_3_v3_snapshot_netG_11.pth --output_path experiments/full_set_predictions/0924_se101_real_painting_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se152_real_clipart_no_aug_round_3_v3_snapshot_netG_10.pth --output_path experiments/full_set_predictions/0924_se152_real_clipart_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/pseudo_label_round_3_0924_v3-models-0924_se152_real_painting_no_aug_round_3_v3_snapshot_netG_9.pth --output_path experiments/full_set_predictions/0924_se152_real_painting_no_aug_round_3_v3_baseline.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64


CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff4_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff4_real_clipart_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff4_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff4_real_painting_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff5_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff5_real_clipart_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff5_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff5_real_painting_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff6_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff6_real_clipart_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff6_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff6_real_painting_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff7_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff7_real_clipart_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff7_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff7_real_painting_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_inception_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_inception_real_clipart_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_inception_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_inception_real_painting_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se101_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se101_real_clipart_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se101_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se101_real_painting_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se152_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se152_real_clipart_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se152_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se152_real_painting_no_aug_round_3_v3_baseline_ema.txt --multi_crop 0 --test_crop_size 224 --test_resize_size 256 --save_feature 1 --test_bs 64


CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff4_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff4_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff4_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff4_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff5_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff5_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff5_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff5_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff6_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff6_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff6_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff6_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff7_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff7_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff7_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff7_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_inception_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_inception_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_inception_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_inception_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se101_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se101_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se101_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se101_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se152_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se152_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se152_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se152_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution.txt --multi_crop 0 --test_crop_size 256 --test_resize_size 288 --save_feature 1 --test_bs 64


CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff4_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff4_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff4_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff4_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff4_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff5_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff5_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff5_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff5_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff5_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff6_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff6_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff6_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff6_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff6_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff7_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff7_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_eff7_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_eff7_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_eff7_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_inception_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_inception_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_inception_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_inception_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_inception_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se101_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se101_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se101_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se101_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se101_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_clipart_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se152_real_clipart_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se152_real_clipart_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 evaluate_models.py --config ./configs/0924_se152_real_painting_no_aug_round_3_v3.yml --netG_model_path experiments/full_set_models/0924_se152_real_painting_no_aug_round_3_v3_snapshot__netG_ema.pth --output_path experiments/full_set_predictions/0924_se152_real_painting_no_aug_round_3_v3_baseline_ema_increase_resolution_no_crop.txt --multi_crop 0 --test_crop_size 320 --test_resize_size 320 --save_feature 1 --test_bs 64
